Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.hostname = "sf-practice-6"
  config.vm.define "sf-practice-6"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "1024"
  end
  config.vm.provision "file", source: "./File.txt", destination: "$HOME/File.txt"
  config.vm.provision "shell", inline: <<-SHELL
    sudo su
    apt update
    apt install python3 python3-pip python3-dev libpq-dev -y
    python3 -m pip install psycopg2 django
  SHELL
end
